name: yptrainer_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.1.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0

dev_dependencies:
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  lints: ^2.0.0
